### ISSUE TITLE
Console warning on deprecated dependency when building with webpack 4

### ISSUE THREAD

**Issue by freefri** [nmccready/debug-fabulous#18]
Hello,
I am using `debug-fabulous` as a dependency of  `gulp-sourcemaps` which depends on `vinyl-fs`, which depends on `module@1.2.5`

`debug-fabulous` depends on `lazy-debug-legacy` https://github.com/apihlaja/lazy-debug which is no longer maintained.

I am getting a warning when building my project with `webpack@4.44.1`

>  WARN  in ./node_modules/lazy-debug-legacy/src/functions.js
>  Critical dependency: the request of a dependency is an expression

And also when running my project:

> ./node_modules/lazy-debug-legacy/src/functions.js 62:15-40
> Critical dependency: the request of a dependency is an expression
> ./node_modules/lazy-debug-legacy/src/functions.js 87:8-28
> Critical dependency: the request of a dependency is an expression

I guess the warning is related with this https://stackoverflow.com/questions/42908116/webpack-critical-dependency-the-request-of-a-dependency-is-an-expression targeting the following lines of the `functions.js` file:

![image](https://user-images.githubusercontent.com/2754631/92717589-be19e700-f360-11ea-8b85-3afa89723dc4.png)

![image](https://user-images.githubusercontent.com/2754631/92717603-c6722200-f360-11ea-8561-2400f4bf70c5.png)

**My question:**

I am wondering if there is a way we can avoid this warning, maybe submitting a MR to `lazy-debug-legacy` project or maybe replacing the dependency of  `lazy-debug-legacy` with something else it is an option.

**Comment by nmccready** [comment]
Thanks I'll take a look. My guess is to remove it as I don't think I hardly use it this portion.

**Comment by nmccready** [comment]
lazy-debug-legacy has been removed
