### ISSUE TITLE
Fix possible memory leak

### ISSUE THREAD

**Issue by nmccready** [nmccready/debug-fabulous#2]
There appears to be a leak in name spacing via spawn.

https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/317

**Comment by nmccready** [comment]
@phated progress or debugging has started here https://github.com/nmccready/debug-fabulous/tree/nmccready/issue2/leak

**Comment by phated** [comment]
@nmccready after a quick review, it looks fine.  Someone in the gulp-sourcemaps thread said it solved their problem, so I think you can ship it.  Sorry for the delay.

**Comment by nmccready** [comment]
@phated cool I'll merge it and cut a version.

**Comment by nmccready** [comment]
Fixes https://github.com/nmccready/debug-fabulous/commit/0d31daaac7d4cce8ec6f2601037c7d907461488d
