### ISSUE TITLE
Please upgrade debug version

### ISSUE THREAD

**Issue by mattgrande** [nmccready/debug-fabulous#3]
NSP released a new ReDoS today; Old versions of `debug` can cause slowdowns.

https://nodesecurity.io/advisories/534

Upgrade to version 2.6.9 or greater if you are on the 2.6.x series or 3.1.0 or greater.

**Comment by nmccready** [comment]
TY; I will look into this ASAP. I will attempt to get something done by the weeks end.

**Comment by nmccready** [comment]
f2e6c96

**Comment by nmccready** [comment]
```
 npm publish
+ debug-fabulous@0.1.2
```

**Comment by mattgrande** [comment]
Thanks!
