### ISSUE TITLE
Explain why this is useful and better than plain `debug` package

### ISSUE THREAD

**Issue by langpavel** [nmccready/debug-fabulous#4]
Please. I don't figure it out in 3 minutes decision making..

**Comment by nmccready** [comment]
Are you asking me to add more info to the Readme.md or do you need it explained here? If you did figure out what is nice about then feel free to make a PR with those details.

In my mind the main improvements and add-ons are:

- lazy log evaluation where it evaluates closures 
 - a string won't be created unless that log level is activated
- DRY namespace creation via `spawn` . You can easily change the root name spacing in one spot without having to replace it in every file.


How to use:

- [original namespace creation](https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/master/src/debug.js) You will reuse this reference
- [look up all the spawns in this file](https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/master/src/write/index.internals.js#L10)

**Comment by langpavel** [comment]
Hi

> Are you asking me to add more info to the Readme.md or do you need it explained here? If you did figure out, then feel free to make a PR with those details.
Yeah, actually both :slightly_smiling_face: 

> lazy log evaluation where it evaluates closures

This is not true in `debug` package?

> a string won't be created unless that log level is activated

Yeah, this is what `debug` package can't handle, but I'm not sure if current V8 will optimize this out, because it can see that result can go to empty function. This can be interesting question on V8 team :slightly_smiling_face: 

> DRY namespace creation via spawn . You can easily change the root name spacing in one spot without having to replace it in every file.

Yeah.. this is something which I cannot understand.. 

BTW have you some benchmarks which can prove that this module is really more performant than original `debug` package?
Interesting benchmark can be if you simply replace `debug` with `debug-fabulous`…

**Comment by nmccready** [comment]
> Yeah, actually both 🙂

Ok I'll update the README.md with more info.






> This is not true in debug package?
Correct, unless they have made some improvements to it. (very possible since its been a while since I have looked at their latest version. They have been more active as of late as well.)




> Yeah, this is what debug package can't handle, but I'm not sure if current V8 will optimize this out, because it can see that result can go to empty function. This can be interesting question on V8 team 🙂

No idea, feel free to research and report your findings. I don't really have the time to dig into this right now (on my limited free time).


> BTW have you some benchmarks which can prove that this module is really more performant than original debug package?
> Interesting benchmark can be if you simply replace debug with debug-fabulous…

Good idea.


Whether you agree or disagree with this package feel free to not use it. I mainly ported this to open source as we used this heavily at a past job and the spawning and lazy loading worked well for us. This was my attempt to give back to the community.

**Comment by langpavel** [comment]
> I don't really have the time to dig into this right now (on my limited free time).

I can say same unfortunately :slightly_smiling_face: 

> I mainly ported this to open source as we used this heavily at a past job and the spawning and lazy loading worked well for us. This was my attempt to give back to the community.

Good job, this is what open source is all about :tada: :heart:

Thanks for your time

**Comment by nmccready** [comment]
@langpavel here are some tests for some proof.

https://github.com/nmccready/debug-fabulous/tree/performanceVsStandardDebug/test/perf

Basically total time is nominally different and insignificant. However where there is much improvement is in memory with using this library.

[Memory without ~ 150 kb](https://github.com/nmccready/debug-fabulous/blob/performanceVsStandardDebug/test/perf/perfWithout.out#L40)

[Memory with ~ 55 kb](https://github.com/nmccready/debug-fabulous/blob/performanceVsStandardDebug/test/perf/perfWith.out#L38)

**Comment by langpavel** [comment]
Ok, looks like it is working better, performance test/proof can show little better time too :-)
You should take this results and mention them in README

**Comment by nmccready** [comment]
yup, will do

**Comment by nmccready** [comment]
Reopening as I need to add these tests to docs and to master.
